// <auto-generated />
using APIDIS2.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIDIS2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200420014106_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIDIS2.Models.Fireball_model+description_fireball", b =>
                {
                    b.Property<string>("date_min")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("date_max");

                    b.Property<string>("energy_max");

                    b.Property<string>("energy_min");

                    b.Property<string>("impact_e_max");

                    b.Property<string>("impact_e_min");

                    b.HasKey("date_min");

                    b.ToTable("description_fireballs");
                });
#pragma warning restore 612, 618
        }
    }
}
